### ISSUE TITLE
Add a button to open search ? 

### ISSUE THREAD

**Issue by cderv** [rstudio/revealjs#141]
With new reveal 4, Search needs to be triggered with CTRL + SHIFT + F. 

We could add a new custom controls to open search too. 

Could be this way : 

````yaml
output: 
  revealjs::revealjs_presentation:
    self_contained: false
    reveal_plugins: 
      - search
      - zoom
      - notes
      - chalkboard
      - menu
    reveal_options:
	  search:
        toggleSearchButton: true
````

But it is not really a reveal option documented in reveal 🤔 
Maybe we should add an argument about controls
