### ISSUE TITLE
Changing the pen color of the chalkboard plugin of reveal.js in RStudio

### ISSUE THREAD

**Issue by grayknight2** [rstudio/revealjs#62]
I´m trying to change the pen color for the chalkboard plugin of reveal.js in RStudio. I have the following code:

```
title: "Presentation"
author: "Me"
date: "2018"
output:
  revealjs::revealjs_presentation:
    theme: league
    transition: convex
    highlight: zenburn
    self_contained: false
    reveal_plugins: ["notes", "zoom", "chalkboard"]
    css: slides.css
    reveal_options:
      chalkboard:
        theme: whiteboard
        color: ['rgba(255, 0, 0, 0.3)'] # red
      previewLinks: true
      slideNumber: true
  beamer_presentation:
    toc: false
    incremental: false 
```  

The color parameter should do the trick, but no matter what color I set I always get a black pen color if I set that parameter (default color is blue). How could I set It to any color I want?

Following the plugin documentation It says I should use: 
color: ['rgba(255, 0, 0, 0.3)', 'rgba(255, 0, 0, 0.3)'] # red, red

This works with "actual" reveal.js, but this gives an error in RStudio, that's why I'm setting only one color. Is there a bug within the RStudio implementation?
