### ISSUE TITLE
Best practice for many presentations

### ISSUE THREAD

**Issue by jdfoote** [rstudio/revealjs#83]
I'm a professor and I have been using revealjs to create presentations for each of my lectures. Each one includes the full javascript for revealjs, and I'm wondering if there's a way to have them all share the same library?

**Comment by jjallaire** [comment]
Keep them in the same directory, and then add to their YAML:

```yaml
output:
   revealjs::revealjs_presentation:
       self_contained: false
       lib_dir: libs
```

A single copy of reveal shared by all of the presentations will end up in the `libs` dir.
