### ISSUE TITLE
Publish several presentations to Github pages

### ISSUE THREAD

**Issue by drfurtado** [rstudio/revealjs#85]
I have all my presentations in a folder and would like the html files to be sent to ../docs upon knit. Currently, the html files are saved in the same directory of the Rmd. files. 

I will then set "docs" in the repo settings (Github) for publishing the presentations (html files).

Below is the content of the _output.yaml file that is saved in the same directory of the .Rmd files (presentations). 

```
revealjs::revealjs_presentation:
  incremental: false
  fig_width: 7
  fig_height: 6
  fig_caption: true
  self_contained: false
  lib_dir: libs
  output_dir: "../docs"
  reveal_plugins: ["chalkboard", "search", "zoom", "notes", "menu"]
  reveal_options:
      slideNumber: true
      previewLinks: true
      chalkboard:
        theme: whiteboard
        toggleNotesButton: true
      menu:
       side: left
       numbers: true
       custom: true
       openButton: true
  theme: default
  transition: slide
  highlight: pygments
  center: false
```
